name: Build and publish a Docker image

on:
  schedule:
  - cron: "0 0 * * 0"

env:
  IMAGE_NAME: gentleman1983/ansible_molecule_debian

jobs:
  docker:
    strategy:
      matrix:
        version: [ 11, 12 ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        build-args: |
          VERSION=${{ matrix.version }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        sbom: true
        push: true
        provenance: mode=max
        build-args: |
          VERSION=${{ matrix.version }}
        tags: |
          gentleman1983/ansible_molecule_debian:${{ matrix.version }}
